export const GET_PERSONS = "GET_PERSONS";
export const GET_BANKS = "GET_BANKS";
export const GET_BALANCE_BANK = "GET_BALANCE_BANK";
export const GET_BALANCE_ACCOUNT = "GET_BALANCE_ACCOUNT";
export const ADD_PERSON = "ADD_PERSON";
export const ADD_BANK = "ADD_BANK";
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const GET_ERRORS = "GET_ERRORS";
export const ADD_ERROR = "ADD_ERROR";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const RESET_ERRORS = "RESET_ERRORS";
export const RESET_ACCOUNTS = "RESET_ACCOUNTS";
export const RESET_TRANSACTIONS = "RESET_TRANSACTIONS";

/* export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const EDIT_MESSAGE = "EDIT_MESSAGE";
export const SEARCH_MESSAGE = "SEARCH_MESSAGE";
export const SET_MESSAGE = "SET_MESSAGE";
export const SET_USERS = "SET_USERS";
export const SET_ROOM = "SET_ROOM";
export const SET_USER_TYPING = "SET_USER_TYPING"; */
