export const GET_USERS = "GET_USERS";
export const GET_BANKS = "GET_BANKS";
export const ADD_USER = "ADD_USER";
export const ADD_BANK = "ADD_BANK";
/* export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const EDIT_MESSAGE = "EDIT_MESSAGE";
export const SEARCH_MESSAGE = "SEARCH_MESSAGE";
export const SET_MESSAGE = "SET_MESSAGE";
export const SET_USERS = "SET_USERS";
export const SET_ROOM = "SET_ROOM";
export const SET_USER_TYPING = "SET_USER_TYPING"; */
